---
title: dev
timezone: UTC
collections:
  uploads:
    title: Uploads
    output: true
  writing:
    output: true
  travel:
    output: true
  work_art_the-handwritten-word:
    output: true
    permalink: "/work/art/the-handwritten-word/:path"
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty